---
- name: Apply host level configuration with oneagentctl
  hosts: dev
  collections:
    - dynatrace.oneagent
  vars:
    oneagent_install_args:
      - "--set-network-zone={{ network_zone }}"
      - "{% if host_group %}--set-host-group={{ host_group }}{% endif %}"
      - "--set-server={{ dynatrace_server }}"
      - "--set-tenant={{ dynatrace_tenant }}"
      - "--restart-service"

  tasks:
    - import_role:
        name: oneagent
